<!-- Comparison Tray (Progressive Enhancement, Max 3 Treks, Zero Ordinary Shadows) -->
<div id="website-compare-tray" class="website-compare-tray" role="region" aria-label="Trek comparison tray" style="display: none;">
    <div class="website-container">
        <div class="website-compare-tray__inner">
            <div class="website-compare-tray__header">
                <div class="website-compare-tray__summary">
                    <span class="website-badge website-badge--warm" style="font-weight: 600;">
                        <span id="website-compare-tray-count">0</span> of 3 selected
                    </span>
                    <span id="website-compare-tray-guidance" class="website-micro website-text-secondary">
                        Select at least 2 treks to compare side-by-side
                    </span>
                </div>

                <div class="website-compare-tray__actions">
                    <button type="button" id="website-compare-clear-btn" class="website-btn website-btn--ghost website-btn--compact" aria-label="Clear all compared treks">
                        Clear All
                    </button>
                    <a id="website-compare-tray-cta" href="{{ route('website.compare') }}" class="website-btn website-btn--primary website-btn--compact" aria-label="View side-by-side comparison of selected treks">
                        <svg class="website-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                            <rect x="3" y="3" width="7" height="18"></rect>
                            <rect x="14" y="3" width="7" height="18"></rect>
                        </svg>
                        <span>Compare Now</span>
                    </a>
                </div>
            </div>

            <!-- List of selected trek chips with remove controls -->
            <div id="website-compare-tray-items" class="website-compare-tray__items" role="list" aria-label="Selected treks for comparison"></div>
        </div>
    </div>
</div>

<!-- Accessible 4th Trek Replacement Modal -->
<div id="website-compare-replace-modal" class="website-dialog" role="dialog" aria-modal="true" aria-labelledby="website-replace-title" style="display: none;">
    <div class="website-dialog__backdrop" id="website-compare-replace-backdrop"></div>
    <div class="website-dialog__panel" style="max-width: 500px;">
        <span class="website-badge website-badge--warm" style="margin-bottom: var(--space-2);">Comparison Limit (Max 3)</span>
        <h3 id="website-replace-title" class="website-h3" style="margin-bottom: var(--space-2);">Replace a Trek to Continue</h3>
        <p class="website-body website-text-secondary" style="margin-bottom: var(--space-4); line-height: 1.5;">
            You can compare up to 3 Himalayan journeys at once. Choose which currently shortlisted trek to replace with <strong id="website-replace-new-name">New Trek</strong>:
        </p>

        <!-- Dynamic list of replace buttons generated by website.js -->
        <div id="website-replace-options" style="display: flex; flex-direction: column; gap: var(--space-2); margin-bottom: var(--space-5);"></div>

        <div style="display: flex; justify-content: flex-end; gap: var(--space-2);">
            <button type="button" id="website-replace-cancel" class="website-btn website-btn--ghost">
                Cancel (Keep Current Selection)
            </button>
        </div>
    </div>
</div>
