<?php

/**
 * Central image manifest for the fixture-only EATH Ways website preview.
 *
 * All photographic slots resolve to authentic Himalayan landscape photography
 * (Everest/Khumbu, Annapurna, Langtang, Manaslu, Upper Mustang) verified with HTTP 200.
 * Fictional website guides (guide-website-01, 02, 03) strictly use neutral illustrated silhouettes.
 */

$neutralGuideSilhouette = static function (string $name, string $role): string {
    $svg = '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800">'
        . '<rect width="100%" height="100%" fill="#f4f2eb"/>'
        . '<circle cx="400" cy="320" r="140" fill="#cbd5d1"/>'
        . '<path d="M 160 760 C 160 560, 260 500, 400 500 C 540 500, 640 560, 640 760 Z" fill="#94a8a1"/>'
        . '<text x="400" y="740" text-anchor="middle" font-family="system-ui, -apple-system, sans-serif" font-size="20" fill="#1b3b36" letter-spacing="1">WEBSITE GUIDE · '.htmlspecialchars(strtoupper($name), ENT_QUOTES, 'UTF-8').'</text>'
        . '</svg>';

    return 'data:image/svg+xml;utf8,' . rawurlencode($svg);
};

return [
    // 1. Homepage & Top-Level Heroes
    'hero-home' => [
        'url' => '/images/hero.webp',
        'mobile_url' => '/images/hero-mobile.webp',
        'alt' => 'Annapurna mountain peaks rising majestically above the Himalayan mist at dawn',
        'width' => 1600,
        'height' => 900,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Local Optimized WebP',
        'license_note' => 'Optimized Local Asset',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'homepage-featured-journey' => [
        'url' => 'https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?auto=format&fit=crop&w=1000&q=75',
        'alt' => 'Expansive high Himalayan valley with snow-capped summits in morning light',
        'width' => 1600,
        'height' => 1000,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Jerry Zhang',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'homepage-safety' => [
        'url' => 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Mountain trekker trekking along a rocky Himalayan trail with guide support',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Toa Heftiba',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'homepage-custom-trip' => [
        'url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=640&q=75',
        'alt' => 'High mountain valley landscape in the Himalayas for bespoke travel planning',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Bailey Zindel',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'homepage-responsible-travel' => [
        'url' => 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Colorful Buddhist prayer flags fluttering above a traditional Himalayan mountain village',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Christopher Burns',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'homepage-travel-guide' => [
        'url' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Sweeping Himalayan mountain ridgelines under deep blue skies',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Kalen Emsley',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 2. Journey Cards (8 Catalog Treks)
    'trek-t-ebc' => [
        'url' => 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Mount Everest and Khumbu glacier high alpine terrain under clear morning skies',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Benjamin Voros',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-abc' => [
        'url' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Annapurna Sanctuary natural amphitheatre framed by towering snow peaks',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Daniel Cheung',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-langtang' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Langtang_Valley_Rasuwa.jpg/1280px-Langtang_Valley_Rasuwa.jpg',
        'alt' => 'Glacial river valley and pine-forested slopes of the serene Langtang National Park',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Langtang Valley Rasuwa',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-mardi' => [
        'url' => 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Narrow mountain ridge trail of Mardi Himal looking toward Machapuchare',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Ales Krivec',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-gokyo' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Gokyo_Lake%2C_Arakamtse%2C_Cholatse%2C_Nepal%2C_Himalayas.jpg/1280px-Gokyo_Lake%2C_Arakamtse%2C_Cholatse%2C_Nepal%2C_Himalayas.jpg',
        'alt' => 'Turquoise glacial waters of Gokyo Lake reflecting Cholatse and Arakamtse peaks',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Gokyo Lake Himalayas',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-manaslu' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/GorkhaManasluConservationArea.jpg/1280px-GorkhaManasluConservationArea.jpg',
        'alt' => 'Remote mountain trail winding through the rugged Manaslu Conservation Area',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Manaslu Conservation Area',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-khopra' => [
        'url' => 'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Alpine ridges and deep green river valleys of the Khopra Danda wilderness',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Robert Bye',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'trek-t-mustang' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Mustang_Valley%2C_Nepal.jpg/1280px-Mustang_Valley%2C_Nepal.jpg',
        'alt' => 'Arid canyon plateaus and sculpted wind-carved cliffs of Upper Mustang',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Mustang Valley Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 3. Geographic Regions (5 Regions)
    'region-everest' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Dole%2C_Boulders_in_the_mountains%2C_Khumbu%2C_Nepal.jpg/1280px-Dole%2C_Boulders_in_the_mountains%2C_Khumbu%2C_Nepal.jpg',
        'alt' => 'Granite boulders and high alpine terrain in the Khumbu Everest region',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Khumbu Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'region-annapurna' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Mount_Annapurna_1.jpg/1280px-Mount_Annapurna_1.jpg',
        'alt' => 'Massive south face of Mount Annapurna rising into cloudless Himalayan skies',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Mount Annapurna 1',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'region-langtang' => [
        'url' => 'https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Forested valley slopes and high snowfields of the Langtang region',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Hendrik Morkel',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'region-manaslu' => [
        'url' => 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Remote rugged mountain passes and deep gorge trails around Mount Manaslu',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Christopher Campbell',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'region-mustang' => [
        'url' => 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=640&q=75',
        'alt' => 'High desert plateau with dramatic eroded sandstone towers in Mustang',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Luca Bravo',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 4. Curated Experiences (6 Experiences)
    'experience-mountain-scenery' => [
        'url' => 'https://images.unsplash.com/photo-1518457607834-6e8d80c183c5?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Sweeping Himalayan mountain panorama bathed in golden morning sunlight',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Joshua Earle',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'experience-cultural-trails' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Prayer_wheels_and_sculptures_around_the_stupa_-_Swayambhunath_%2817824978016%29.jpg/1280px-Prayer_wheels_and_sculptures_around_the_stupa_-_Swayambhunath_%2817824978016%29.jpg',
        'alt' => 'Traditional Buddhist prayer wheels along an ancient pilgrimage trail',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Swayambhunath Stupa',
        'license_note' => 'Creative Commons Attribution-ShareAlike 2.0 Generic',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'experience-quiet-trails' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Nepal_Tribeni_Trek.jpg/1280px-Nepal_Tribeni_Trek.jpg',
        'alt' => 'Solitary trail through pristine Himalayan forests away from crowded trekking routes',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Nepal Tribeni Trek',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'experience-short-treks' => [
        'url' => 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Ghorepani_poon_hill_._Mesmerizing_Sun_rise.jpg',
        'alt' => 'Sunrise over the Dhaulagiri and Annapurna mountain ranges from Poon Hill',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Ghorepani Poon Hill',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'experience-photography' => [
        'url' => 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Alpine mirror lake reflecting snow-capped Himalayan peaks in sharp morning clarity',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Sergei A',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'experience-iconic-routes' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Ama_Dablam%2C_Nepal.jpg/1280px-Ama_Dablam%2C_Nepal.jpg',
        'alt' => 'Iconic pyramid silhouette of Mount Ama Dablam rising above the Khumbu Valley',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Ama Dablam Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 5. Website Guides (Strict Neutral Illustrated Silhouettes)
    'guide-website-01' => [
        'url' => $neutralGuideSilhouette('Pemba Sherpa', 'Lead Mountain Guide'),
        'alt' => 'Neutral illustrated silhouette representation for fictional website guide Pemba Sherpa',
        'width' => 800,
        'height' => 800,
        'aspect_ratio' => '1:1',
        'focal_point' => 'center',
        'source' => 'Local deterministic vector silhouette',
        'license_note' => 'Fictional website guide avatar; no real person depicted',
        'is_website' => true,
        'is_fallback' => true,
    ],
    'guide-website-02' => [
        'url' => $neutralGuideSilhouette('Dawa Tamang', 'Wilderness & Cultural Specialist'),
        'alt' => 'Neutral illustrated silhouette representation for fictional website guide Dawa Tamang',
        'width' => 800,
        'height' => 800,
        'aspect_ratio' => '1:1',
        'focal_point' => 'center',
        'source' => 'Local deterministic vector silhouette',
        'license_note' => 'Fictional website guide avatar; no real person depicted',
        'is_website' => true,
        'is_fallback' => true,
    ],
    'guide-website-03' => [
        'url' => $neutralGuideSilhouette('Maya Gurung', 'High-Altitude Trek Specialist'),
        'alt' => 'Neutral illustrated silhouette representation for fictional website guide Maya Gurung',
        'width' => 800,
        'height' => 800,
        'aspect_ratio' => '1:1',
        'focal_point' => 'center',
        'source' => 'Local deterministic vector silhouette',
        'license_note' => 'Fictional website guide avatar; no real person depicted',
        'is_website' => true,
        'is_fallback' => true,
    ],

    // 6. Traveler Stories (3 Website Stories)
    'story-website-01' => [
        'url' => 'https://images.unsplash.com/photo-1533240332313-0db49b459ad6?auto=format&fit=crop&w=640&q=75',
        'alt' => 'High mountain pass in the Himalayas bathed in early morning golden light',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Simon English',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'story-website-02' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/Namche_Bazaar%2C_Nepal.jpg/1280px-Namche_Bazaar%2C_Nepal.jpg',
        'alt' => 'Traditional stone lodges of Namche Bazaar nestled into the mountain bowl',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Namche Bazaar Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'story-website-03' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Early_morning_light_at_the_top_of_Poon_Hill1.jpg/1280px-Early_morning_light_at_the_top_of_Poon_Hill1.jpg',
        'alt' => 'First dawn rays illuminating the Annapurna mountain ridge from Poon Hill',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Early morning light Poon Hill',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 7. Travel Guide Articles (6 Articles)
    'article-seasons' => [
        'url' => 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Crystal clear autumn mountain skies across the central Nepal Himalayas',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Tobias Keller',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'article-packing' => [
        'url' => 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=640&q=75',
        'alt' => 'Rocky trail pathway through high Himalayan terrain showing practical gear environment',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Unsplash / Dan Meyers',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'article-altitude' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Cho_La_Pass%2C_Crossing%2C_Nepal%2C_Himalayas.jpg/1280px-Cho_La_Pass%2C_Crossing%2C_Nepal%2C_Himalayas.jpg',
        'alt' => 'High-altitude snow and glacial crossing at Cho La Pass 5420 meters',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Cho La Pass Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'article-compare' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Langtang_Trekking_Trail_2.jpg/1280px-Langtang_Trekking_Trail_2.jpg',
        'alt' => 'Stone footpath winding through Himalayan valleys for comparing trekking routes',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Langtang Trekking Trail',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'article-culture' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Tengboche_Monastery_during_winter.jpg/1280px-Tengboche_Monastery_during_winter.jpg',
        'alt' => 'Historic Tengboche Monastery surrounded by snow-covered peaks in the Khumbu region',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Tengboche Monastery',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'article-logistics' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Jhinu_bridge.jpg/1280px-Jhinu_bridge.jpg',
        'alt' => 'Himalayan suspension bridge carrying trekkers safely across a deep mountain river gorge',
        'width' => 1280,
        'height' => 800,
        'aspect_ratio' => '16:10',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Jhinu Bridge Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 4.0 International',
        'is_website' => true,
        'is_fallback' => false,
    ],

    // 8. Institutional & Safety Pages (5 Heroes)
    'about-hero' => [
        'url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1000&q=75',
        'alt' => 'Vast panoramic view of the Greater Himalaya mountain chain at sunrise',
        'width' => 1600,
        'height' => 900,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Unsplash / Ashim DSilva',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'safety-hero' => [
        'url' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Himalayas%2C_Ama_Dablam%2C_Nepal.jpg/1920px-Himalayas%2C_Ama_Dablam%2C_Nepal.jpg',
        'alt' => 'Expansive alpine ridgeline beneath the iconic summit of Ama Dablam',
        'width' => 1920,
        'height' => 1080,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Wikimedia Commons / Himalayas Ama Dablam Nepal',
        'license_note' => 'Creative Commons Attribution-ShareAlike 3.0 Unported',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'responsible-travel-hero' => [
        'url' => 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=75',
        'alt' => 'Untouched mountain wilderness and pristine river valley in Nepal',
        'width' => 1600,
        'height' => 900,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Unsplash / Luca Bravo',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'contact-hero' => [
        'url' => 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=1000&q=75',
        'alt' => 'Serene morning atmosphere overlooking the Himalayan foothills',
        'width' => 1600,
        'height' => 900,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Unsplash / Tom Vining',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
    'faq-hero' => [
        'url' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1000&q=75',
        'alt' => 'Tranquil glacial waters framed by dramatic mountain summits',
        'width' => 1600,
        'height' => 900,
        'aspect_ratio' => '16:9',
        'focal_point' => 'center',
        'source' => 'Unsplash / Luca Bravo',
        'license_note' => 'Unsplash Free Commercial License',
        'is_website' => true,
        'is_fallback' => false,
    ],
];
